### ISSUE TITLE
Search Functionality Not Working on "Admins" and "Employees" Page.

### ISSUE THREAD

**Issue by thapaaashish** [sarthak2331183/HRMS-PROJECT#1]
The search functionality on the admin page of our HRMS is not functioning as expected. When attempting to use the search feature to find specific items or records, no results are returned, and the search field appears unresponsive.

**Comment by thapaaashish** [comment]
It's also not working on the "Employees" page.

**Comment by swechhyamaharjan** [comment]
I have made work search and sort functionalities.
