### ISSUE TITLE
Employee can't see all the projects assigned to them.

### ISSUE THREAD

**Issue by thapaaashish** [sarthak2331183/HRMS-PROJECT#10]
Problem: Employees are unable to view all the projects that have been assigned to them, affecting their ability to manage their work effectively.

Expected Behavior: Employees should see a complete list of all projects assigned to them.

Actual Behavior: Employees goes to a project details page without showing the list of projects assigned to them.

**Comment by anivmaharjan** [comment]
Thanks for heads up!
