### ISSUE TITLE
Admin unable to save the edit in about project page.

### ISSUE THREAD

**Issue by thapaaashish** [sarthak2331183/HRMS-PROJECT#13]
Admin is unable to save edits on the "About Project" page. The issue occurs after making changes and attempting to save. Add a save button.

![image](https://github.com/sarthak2331183/HRMS-PROJECT/assets/119116507/27b22242-dd01-4d5b-a05d-4c7e1d0299f1)

**Comment by sarthak2331183** [comment]
This section requires a modification in the frontend aspect. We should discuss this together to determine the best approach moving forward.

**Comment by ShrijanThapa77** [comment]
Noted .
