### ISSUE TITLE
Runtime error when clicking "Leave" in the navbar while on the leave page.

### ISSUE THREAD

**Issue by thapaaashish** [sarthak2331183/HRMS-PROJECT#14]
When the "Leave" link in the navbar is clicked while the user is already on the 'leave" page, a runtime error occurs. Disrupting the functionality of the page and affecting user experience.

Expected Behavior:
Clicking "Leave" in the navbar while on the leave page should refresh the page or navigate without errors.

Actual Behavior:
A runtime error appears when the "Leave" link is clicked in the navbar while already on the leave page.

**Comment by anivmaharjan** [comment]
Thank you for addressing the issue , i have done the necessary part.
