### ISSUE TITLE
Data not displayed properly when clicking all, pending, approved, and denied buttons in Leave page.

### ISSUE THREAD

**Issue by thapaaashish** [sarthak2331183/HRMS-PROJECT#15]
When clicking the "All", "Pending", "Approved", and "Denied" buttons on the Leave page, the data displayed is not correct. It either shows incorrect, or incomplete.

**Comment by sarthak2331183** [comment]
From Admin side or Employee side??

**Comment by thapaaashish** [comment]
For admin.

**Comment by ShrijanThapa77** [comment]
this part is done .
