### ISSUE TITLE
It does not show the navbar properly when we are on the project detail page of the employee.

### ISSUE THREAD

**Issue by thapaaashish** [sarthak2331183/HRMS-PROJECT#16]
It does not show the navbar properly when we are on the project detail page of the employee. It should show all the employee pages i.e. leave, attendance, projects, and dashboard.

![image](https://github.com/sarthak2331183/HRMS-PROJECT/assets/119116507/496aeef4-b971-4247-bb3c-a1e745d4baae)

**Comment by ShrijanThapa77** [comment]
issue is fixed as the project page is now changed.
