### ISSUE TITLE
Nothing happens when an employee clicks on the calendar button.

### ISSUE THREAD

**Issue by thapaaashish** [sarthak2331183/HRMS-PROJECT#17]
Nothing happens when an employee clicks on the calendar button.
It should show the option to click a certain date to see the attendance of that date.
![image](https://github.com/sarthak2331183/HRMS-PROJECT/assets/119116507/836a3220-0ec2-4d62-baf1-2fe2ec0a7621)

**Comment by anivmaharjan** [comment]
Noted, the issue has been fixed
