### ISSUE TITLE
Greetings Not Displaying According to User's Local Time.

### ISSUE THREAD

**Issue by thapaaashish** [sarthak2331183/HRMS-PROJECT#2]
The greetings feature in the admin dashboard is not adjusting the greeting message according to the user's local time. For example, if it's afternoon in the user's time zone, the greeting should say "Good afternoon," but it's not doing so consistently.

**Comment by swechhyamaharjan** [comment]
okay, I will work on the implementation of the greetings feature and identify any potential bugs in the code.

**Comment by swechhyamaharjan** [comment]
Above issue has been solved.
