### ISSUE TITLE
Search feature doesn't work in attendance page of admin.

### ISSUE THREAD

**Issue by thapaaashish** [sarthak2331183/HRMS-PROJECT#7]
The search feature on the attendance page in the admin section is currently not functioning. When attempting to search for specific entries, the expected results are not displayed, making it difficult to find the required records.

**Comment by swechhyamaharjan** [comment]
Sure, I will fix that bug.

**Comment by swechhyamaharjan** [comment]
The search feature is working properly now. You can check it out. 
<img width="1483" alt="Screenshot 2024-05-15 at 11 54 23 AM" src="https://github.com/sarthak2331183/HRMS-PROJECT/assets/119122826/47193bbc-4834-4851-a513-3eceef265a86">
