### ISSUE TITLE
Sort by feature doesn't work on attendance page of admin.

### ISSUE THREAD

**Issue by thapaaashish** [sarthak2331183/HRMS-PROJECT#8]
The "Sort by" feature on the attendance page in the admin section is not functioning correctly. When attempting to sort the attendance records by various columns (e.g., date, name), the records are not sorted as expected.
![image](https://github.com/sarthak2331183/HRMS-PROJECT/assets/119116507/c0aa323d-4b00-430d-9efe-781c6097a30a)

**Comment by swechhyamaharjan** [comment]
I will fix the issue as soon as possible.

**Comment by swechhyamaharjan** [comment]
Sort functionality is working smoothly now.
<img width="1316" alt="Screenshot 2024-05-15 at 11 57 46 AM" src="https://github.com/sarthak2331183/HRMS-PROJECT/assets/119122826/e5289a5c-f84b-4ba2-afa8-c10b8c3b8980">
