### ISSUE TITLE
Project Buttons Not Displaying Projects Correctly

### ISSUE THREAD

**Issue by thapaaashish** [sarthak2331183/HRMS-PROJECT#9]
The projects are not displaying as per the buttons on the project page for both admin and employee roles. When an admin or an employee clicks on the respective buttons to view projects, the projects do not appear as expected.
![image](https://github.com/sarthak2331183/HRMS-PROJECT/assets/119116507/35031c92-01b5-4e8d-bfe8-cfde3dd0ce50)

**Comment by swechhyamaharjan** [comment]
Sorry for that. The issue has been fixed now. You can check them.
<img width="1469" alt="Screenshot 2024-05-16 at 8 03 08 PM" src="https://github.com/sarthak2331183/HRMS-PROJECT/assets/119122826/91a3394f-addc-4608-b69e-761e20b1d441">

.
